# Set theme
#remote_theme: daviddarnes/alembic
remote_theme: thelehhman/plainwhite-jekyll

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://inigo.info'
baseurl: ''
title: 'iñigo'
description: 'info'
permalink: pretty
logo: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=52"
#date_format: "%Y %M %D"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Blog
  url: /blog/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

plainwhite:
  name: Iñigo Alonso Fernandez
  tagline: Engineer, PhD Student
  date_format: "%b %-d, %Y"

  social_links:
    twitter: inigoalonso
    github:  inigoalonso
    linkedIn: en/inigoalonso # format: locale/username