# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
url: 'https://inigo.info'
baseurl: ''
title: 'iñigo'
description: 'info'
permalink: pretty
logo: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=52"
#date_format: "%Y %M %D"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Blog
  url: /blog/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

plainwhite:
  name: Iñigo Alonso Fernandez
  tagline: Engineer, PhD Student
  date_format: "%b %-d, %Y"

  social_links:
    twitter: inigoalonso
    github:  inigoalonso
    linkedIn: in/inigoalonso # format: locale/username
